/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicativo.pizzaria.gui;

import aplicativo.pizzaria.bo.UserBO;
import aplicativo.pizzaria.dto.UserDTO;
import aplicativo.pizzaria.exception.NegocioException;
import aplicativo.pizzaria.main.Main;
import aplicativo.pizzaria.util.MensagensUtil;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduardo
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        String tipo = null;
        try {
            tipo = UserBO.tipo(Main.getUsuarioLogado().getTipo());
        } catch (NegocioException ex) {
            ex.printStackTrace();
            MensagensUtil.addMsg(MainFrame.this, ex.getMessage());
        }
        LbLogin.setText(Main.getUsuarioLogado().getNome());
        LbTipo.setText(tipo);
        if (Main.getUsuarioLogado().getTipo() > 0) {
            TabPrincipal.remove(TabUsuarios);
            TabPrincipal.remove(TabProdutos);
        }
        if (Main.getUsuarioLogado().getTipo() > 1) {
            TabPrincipal.remove(TabClientes);
            TabPedidos.remove(Novo);
        }
        if (Main.getUsuarioLogado().getTipo() > 2) {
        }
        atualizarTabela();
        CBoxTipoB.setSelectedIndex(4);
    }

    public void atualizarCampos(Integer id, int tipo, String nome, String login) {
        TxtIdA.setText(String.valueOf(id));
        CBoxTipoA.setSelectedIndex(tipo);
        TxtNomeA.setText(nome);
        TxtLoginA.setText(login);
    }

    public void limparCampos() {
        for (int i = 0; i < getContentPane().getComponentCount(); i++) {
            Component c = getContentPane().getComponent(i);
            if (c instanceof JTextField) { 
                JTextField field = (JTextField) c;
                field.setText("");
            }
        }
    }

    public final void atualizarTabela() {
        UserBO listaBo = new UserBO();
        List<UserDTO> lista = new ArrayList<>();
        DefaultTableModel tbl = (DefaultTableModel) TblUser.getModel();
        try {
            lista = listaBo.listar();
            while (tbl.getRowCount() > 0) {
                tbl.removeRow(0);
            }
            int i = 0;
            for (UserDTO user : lista) {
                tbl.addRow(new String[1]);
                TblUser.setValueAt(user.getId(), i, 0);
                TblUser.setValueAt(user.getNome(), i, 1);
                TblUser.setValueAt(user.getLogin(), i, 2);
                try {
                    TblUser.setValueAt(UserBO.tipo(user.getTipo()), i, 3);
                } catch (NegocioException ex) {
                    ex.printStackTrace();
                    MensagensUtil.addMsg(MainFrame.this, ex.getMessage());
                }
                i++;
            }
        } catch (NegocioException ex) {
            ex.printStackTrace();
            MensagensUtil.addMsg(MainFrame.this, ex.getMessage());
        }
    }

    public void atualizarTabela(List<UserDTO> consulta) {
        if (consulta != null) {
            DefaultTableModel tbl = (DefaultTableModel) TblUser.getModel();
            while (tbl.getRowCount() > 0) {
                tbl.removeRow(0);
            }
            int i = 0;
            for (UserDTO user : consulta) {
                tbl.addRow(new String[1]);
                TblUser.setValueAt(user.getId(), i, 0);
                TblUser.setValueAt(user.getNome(), i, 1);
                TblUser.setValueAt(user.getLogin(), i, 2);
                try {
                    TblUser.setValueAt(UserBO.tipo(user.getTipo()), i, 3);
                } catch (NegocioException ex) {
                    ex.printStackTrace();
                    MensagensUtil.addMsg(MainFrame.this, ex.getMessage());
                }
                i++;
            }
        } else {
            atualizarTabela();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Usuario = new javax.swing.JPanel();
        LbLogin = new javax.swing.JLabel();
        Tipo = new javax.swing.JPanel();
        LbTipo = new javax.swing.JLabel();
        TabPrincipal = new javax.swing.JTabbedPane();
        TabUsuarios = new javax.swing.JTabbedPane();
        CadastroUsuario = new javax.swing.JPanel();
        LabLoginC = new javax.swing.JLabel();
        LabSenhaC = new javax.swing.JLabel();
        LabSenhaRC = new javax.swing.JLabel();
        LabTipoC = new javax.swing.JLabel();
        LabNomeC = new javax.swing.JLabel();
        TxtUserC = new javax.swing.JTextField();
        TxtSenhaC = new javax.swing.JPasswordField();
        TxtSenhaRC = new javax.swing.JPasswordField();
        CBoxTipoC = new javax.swing.JComboBox();
        TxtNomeC = new javax.swing.JTextField();
        ButCadastroC = new javax.swing.JButton();
        ListaUsuario = new javax.swing.JPanel();
        ScrollPaneTab = new javax.swing.JScrollPane();
        TblUser = new javax.swing.JTable();
        ButAtualizarL = new javax.swing.JButton();
        BuscaUsuario = new javax.swing.JPanel();
        LabIdB = new javax.swing.JLabel();
        LabLoginB = new javax.swing.JLabel();
        LabTipoB = new javax.swing.JLabel();
        LabNomeB = new javax.swing.JLabel();
        TxtIdB = new javax.swing.JTextField();
        TxtLoginB = new javax.swing.JTextField();
        CBoxTipoB = new javax.swing.JComboBox();
        TxtNomeB = new javax.swing.JTextField();
        ButBuscarB = new javax.swing.JButton();
        AlteraUsuario = new javax.swing.JPanel();
        LabIdA = new javax.swing.JLabel();
        LabLoginA = new javax.swing.JLabel();
        LabSenhaA = new javax.swing.JLabel();
        LabSenhaNA = new javax.swing.JLabel();
        LabSenhaNRA = new javax.swing.JLabel();
        LabTipoA = new javax.swing.JLabel();
        LabNomeA = new javax.swing.JLabel();
        TxtLoginA = new javax.swing.JTextField();
        TxtIdA = new javax.swing.JTextField();
        TxtSenhaNA = new javax.swing.JPasswordField();
        TxtSenhaN2A = new javax.swing.JPasswordField();
        CBoxTipoA = new javax.swing.JComboBox();
        TxtNomeA = new javax.swing.JTextField();
        ButExcluirA = new javax.swing.JButton();
        ButAlterarA = new javax.swing.JButton();
        TxtSenhaA = new javax.swing.JPasswordField();
        TabPedidos = new javax.swing.JTabbedPane();
        Novo = new javax.swing.JPanel();
        ListaPedido = new javax.swing.JPanel();
        ScrollPaneTab2 = new javax.swing.JScrollPane();
        TblPedido = new javax.swing.JTable();
        ButAtualizarPL = new javax.swing.JButton();
        AlteraPedido = new javax.swing.JPanel();
        TabProdutos = new javax.swing.JTabbedPane();
        CadastroProduto = new javax.swing.JPanel();
        ListaProduto = new javax.swing.JPanel();
        ScrollPaneTab3 = new javax.swing.JScrollPane();
        TblProduto = new javax.swing.JTable();
        ButAtualizarPrL = new javax.swing.JButton();
        AlteraProduto = new javax.swing.JPanel();
        TabClientes = new javax.swing.JTabbedPane();
        CadastroCliente = new javax.swing.JPanel();
        ListaCliente = new javax.swing.JPanel();
        ScrollPaneTab4 = new javax.swing.JScrollPane();
        TblCliente = new javax.swing.JTable();
        ButAtualizarCL = new javax.swing.JButton();
        AlteraCliente = new javax.swing.JPanel();
        ButSair = new javax.swing.JButton();
        ButLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        Usuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário"));

        LbLogin.setText("Login");

        javax.swing.GroupLayout UsuarioLayout = new javax.swing.GroupLayout(Usuario);
        Usuario.setLayout(UsuarioLayout);
        UsuarioLayout.setHorizontalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLayout.createSequentialGroup()
                .addComponent(LbLogin)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        UsuarioLayout.setVerticalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbLogin)
        );

        Tipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Perfil"));

        LbTipo.setText("Tipo");

        javax.swing.GroupLayout TipoLayout = new javax.swing.GroupLayout(Tipo);
        Tipo.setLayout(TipoLayout);
        TipoLayout.setHorizontalGroup(
            TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TipoLayout.createSequentialGroup()
                .addComponent(LbTipo)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        TipoLayout.setVerticalGroup(
            TipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbTipo, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        TabUsuarios.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        TabUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CadastroUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário"));

        LabLoginC.setText("Usuário");

        LabSenhaC.setText("Senha");

        LabSenhaRC.setText("Repita senha");

        LabTipoC.setText("Tipo");

        LabNomeC.setText("Nome");

        CBoxTipoC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Atendente", "Pizzaiolo", "Entregador" }));

        ButCadastroC.setText("Cadastrar");
        ButCadastroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCadastroCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadastroUsuarioLayout = new javax.swing.GroupLayout(CadastroUsuario);
        CadastroUsuario.setLayout(CadastroUsuarioLayout);
        CadastroUsuarioLayout.setHorizontalGroup(
            CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroUsuarioLayout.createSequentialGroup()
                        .addComponent(LabSenhaRC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(TxtSenhaRC, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastroUsuarioLayout.createSequentialGroup()
                        .addComponent(LabTipoC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBoxTipoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroUsuarioLayout.createSequentialGroup()
                        .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabLoginC)
                            .addComponent(LabSenhaC)
                            .addComponent(LabNomeC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtUserC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(TxtSenhaC))
                            .addComponent(TxtNomeC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroUsuarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButCadastroC))
        );

        CadastroUsuarioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TxtNomeC, TxtSenhaC, TxtSenhaRC, TxtUserC});

        CadastroUsuarioLayout.setVerticalGroup(
            CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabNomeC)
                    .addComponent(TxtNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabLoginC)
                    .addComponent(TxtUserC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabSenhaC)
                    .addComponent(TxtSenhaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabSenhaRC)
                    .addComponent(TxtSenhaRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTipoC)
                    .addComponent(CBoxTipoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(ButCadastroC))
        );

        TabUsuarios.addTab("Cadastrar", CadastroUsuario);

        ListaUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela"));

        ScrollPaneTab.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Login", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblUserMouseClicked(evt);
            }
        });
        ScrollPaneTab.setViewportView(TblUser);

        ButAtualizarL.setText("Atualizar");
        ButAtualizarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAtualizarLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListaUsuarioLayout = new javax.swing.GroupLayout(ListaUsuario);
        ListaUsuario.setLayout(ListaUsuarioLayout);
        ListaUsuarioLayout.setHorizontalGroup(
            ListaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPaneTab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(ListaUsuarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButAtualizarL))
        );
        ListaUsuarioLayout.setVerticalGroup(
            ListaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneTab, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButAtualizarL))
        );

        TabUsuarios.addTab("Listar", ListaUsuario);

        BuscaUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário"));

        LabIdB.setText("ID:");

        LabLoginB.setText("Login:");

        LabTipoB.setText("Tipo:");

        LabNomeB.setText("Nome:");

        CBoxTipoB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Atendente", "Pizzaiolo", "Entregador", "Nenhum" }));
        CBoxTipoB.setToolTipText("");

        ButBuscarB.setText("Buscar");
        ButBuscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButBuscarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscaUsuarioLayout = new javax.swing.GroupLayout(BuscaUsuario);
        BuscaUsuario.setLayout(BuscaUsuarioLayout);
        BuscaUsuarioLayout.setHorizontalGroup(
            BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabIdB)
                    .addComponent(LabLoginB)
                    .addComponent(LabTipoB)
                    .addComponent(LabNomeB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CBoxTipoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtLoginB)
                    .addComponent(TxtNomeB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtIdB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscaUsuarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButBuscarB))
        );

        BuscaUsuarioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TxtLoginB, TxtNomeB});

        BuscaUsuarioLayout.setVerticalGroup(
            BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabIdB)
                    .addComponent(TxtIdB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTipoB)
                    .addComponent(CBoxTipoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabNomeB)
                    .addComponent(TxtNomeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuscaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabLoginB)
                    .addComponent(TxtLoginB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButBuscarB))
        );

        TabUsuarios.addTab("Buscar", BuscaUsuario);

        AlteraUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário"));

        LabIdA.setText("ID:");

        LabLoginA.setText("Login:");

        LabSenhaA.setText("Senha:");

        LabSenhaNA.setText("Nova senha:");

        LabSenhaNRA.setText("Repita senha:");

        LabTipoA.setText("Tipo:");

        LabNomeA.setText("Nome:");

        TxtIdA.setEditable(false);

        CBoxTipoA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Atendente", "Pizzaiolo", "Entregador" }));

        ButExcluirA.setText("Excluir");
        ButExcluirA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExcluirAActionPerformed(evt);
            }
        });

        ButAlterarA.setText("Alterar");
        ButAlterarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAlterarAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AlteraUsuarioLayout = new javax.swing.GroupLayout(AlteraUsuario);
        AlteraUsuario.setLayout(AlteraUsuarioLayout);
        AlteraUsuarioLayout.setHorizontalGroup(
            AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlteraUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlteraUsuarioLayout.createSequentialGroup()
                        .addComponent(LabIdA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtIdA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AlteraUsuarioLayout.createSequentialGroup()
                        .addComponent(LabTipoA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBoxTipoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AlteraUsuarioLayout.createSequentialGroup()
                        .addComponent(LabLoginA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtLoginA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AlteraUsuarioLayout.createSequentialGroup()
                        .addComponent(LabNomeA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtNomeA, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AlteraUsuarioLayout.createSequentialGroup()
                        .addComponent(LabSenhaA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtSenhaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AlteraUsuarioLayout.createSequentialGroup()
                        .addComponent(LabSenhaNRA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtSenhaN2A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AlteraUsuarioLayout.createSequentialGroup()
                        .addComponent(LabSenhaNA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtSenhaNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlteraUsuarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButExcluirA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButAlterarA))
        );

        AlteraUsuarioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TxtLoginA, TxtNomeA, TxtSenhaA, TxtSenhaN2A, TxtSenhaNA});

        AlteraUsuarioLayout.setVerticalGroup(
            AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlteraUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabIdA)
                    .addComponent(TxtIdA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTipoA)
                    .addComponent(CBoxTipoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabNomeA)
                    .addComponent(TxtNomeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabLoginA)
                    .addComponent(TxtLoginA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabSenhaA)
                    .addComponent(TxtSenhaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabSenhaNA)
                    .addComponent(TxtSenhaNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabSenhaNRA)
                    .addComponent(TxtSenhaN2A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AlteraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButAlterarA)
                    .addComponent(ButExcluirA)))
        );

        TabUsuarios.addTab("Alterar", AlteraUsuario);

        TabPrincipal.addTab("Usuários", TabUsuarios);

        javax.swing.GroupLayout NovoLayout = new javax.swing.GroupLayout(Novo);
        Novo.setLayout(NovoLayout);
        NovoLayout.setHorizontalGroup(
            NovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        NovoLayout.setVerticalGroup(
            NovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        TabPedidos.addTab("Novo", Novo);

        ListaPedido.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela"));

        ScrollPaneTab2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Login", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblPedidoMouseClicked(evt);
            }
        });
        ScrollPaneTab2.setViewportView(TblPedido);

        ButAtualizarPL.setText("Atualizar");
        ButAtualizarPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAtualizarPLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListaPedidoLayout = new javax.swing.GroupLayout(ListaPedido);
        ListaPedido.setLayout(ListaPedidoLayout);
        ListaPedidoLayout.setHorizontalGroup(
            ListaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPaneTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(ListaPedidoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButAtualizarPL))
        );
        ListaPedidoLayout.setVerticalGroup(
            ListaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneTab2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButAtualizarPL))
        );

        TabPedidos.addTab("Listar", ListaPedido);

        javax.swing.GroupLayout AlteraPedidoLayout = new javax.swing.GroupLayout(AlteraPedido);
        AlteraPedido.setLayout(AlteraPedidoLayout);
        AlteraPedidoLayout.setHorizontalGroup(
            AlteraPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        AlteraPedidoLayout.setVerticalGroup(
            AlteraPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        TabPedidos.addTab("Alterar", AlteraPedido);

        TabPrincipal.addTab("Pedidos", TabPedidos);

        javax.swing.GroupLayout CadastroProdutoLayout = new javax.swing.GroupLayout(CadastroProduto);
        CadastroProduto.setLayout(CadastroProdutoLayout);
        CadastroProdutoLayout.setHorizontalGroup(
            CadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        CadastroProdutoLayout.setVerticalGroup(
            CadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        TabProdutos.addTab("Cadastrar", CadastroProduto);

        ListaProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela"));

        ScrollPaneTab3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Login", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblProdutoMouseClicked(evt);
            }
        });
        ScrollPaneTab3.setViewportView(TblProduto);

        ButAtualizarPrL.setText("Atualizar");
        ButAtualizarPrL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAtualizarPrLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListaProdutoLayout = new javax.swing.GroupLayout(ListaProduto);
        ListaProduto.setLayout(ListaProdutoLayout);
        ListaProdutoLayout.setHorizontalGroup(
            ListaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPaneTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(ListaProdutoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButAtualizarPrL))
        );
        ListaProdutoLayout.setVerticalGroup(
            ListaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneTab3, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButAtualizarPrL))
        );

        TabProdutos.addTab("Listar", ListaProduto);

        javax.swing.GroupLayout AlteraProdutoLayout = new javax.swing.GroupLayout(AlteraProduto);
        AlteraProduto.setLayout(AlteraProdutoLayout);
        AlteraProdutoLayout.setHorizontalGroup(
            AlteraProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        AlteraProdutoLayout.setVerticalGroup(
            AlteraProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        TabProdutos.addTab("Alterar", AlteraProduto);

        TabPrincipal.addTab("Produtos", TabProdutos);

        javax.swing.GroupLayout CadastroClienteLayout = new javax.swing.GroupLayout(CadastroCliente);
        CadastroCliente.setLayout(CadastroClienteLayout);
        CadastroClienteLayout.setHorizontalGroup(
            CadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        CadastroClienteLayout.setVerticalGroup(
            CadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        TabClientes.addTab("Cadastrar", CadastroCliente);

        ListaCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela"));

        ScrollPaneTab4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Login", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblClienteMouseClicked(evt);
            }
        });
        ScrollPaneTab4.setViewportView(TblCliente);

        ButAtualizarCL.setText("Atualizar");
        ButAtualizarCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAtualizarCLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListaClienteLayout = new javax.swing.GroupLayout(ListaCliente);
        ListaCliente.setLayout(ListaClienteLayout);
        ListaClienteLayout.setHorizontalGroup(
            ListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPaneTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(ListaClienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButAtualizarCL))
        );
        ListaClienteLayout.setVerticalGroup(
            ListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneTab4, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButAtualizarCL))
        );

        TabClientes.addTab("Listar", ListaCliente);

        javax.swing.GroupLayout AlteraClienteLayout = new javax.swing.GroupLayout(AlteraCliente);
        AlteraCliente.setLayout(AlteraClienteLayout);
        AlteraClienteLayout.setHorizontalGroup(
            AlteraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        AlteraClienteLayout.setVerticalGroup(
            AlteraClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        TabClientes.addTab("Alterar", AlteraCliente);

        TabPrincipal.addTab("Clientes", TabClientes);

        ButSair.setText("Sair");
        ButSair.setToolTipText("");
        ButSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSairActionPerformed(evt);
            }
        });

        ButLogout.setText("Logout");
        ButLogout.setToolTipText("");
        ButLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButLogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Tipo, Usuario});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButSair)
                    .addComponent(ButLogout))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ButSairActionPerformed

    private void TblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblUserMouseClicked
        if (Main.getUsuarioLogado().getTipo() < 2) {
            Integer linha = TblUser.getSelectedRow();
            TabUsuarios.setSelectedComponent(AlteraUsuario);
            try {
                atualizarCampos((Integer) TblUser.getValueAt(linha, 0),
                        UserBO.escolherTipo((String) TblUser.getValueAt(linha, 3)),
                        (String) TblUser.getValueAt(linha, 1),
                        (String) TblUser.getValueAt(linha, 2));
                /*TxtIdA.setText(String.valueOf((Integer) TblUser.getValueAt(linha, 0)));
                 CBoxTipoA.setSelectedIndex(UserBO.escolherTipo((String) TblUser.getValueAt(linha, 3)));
                 TxtNomeA.setText((String) TblUser.getValueAt(linha, 1));
                 TxtLoginA.setText((String) TblUser.getValueAt(linha, 2));*/
            } catch (NegocioException ex) {
                ex.printStackTrace();
                MensagensUtil.addMsg(MainFrame.this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_TblUserMouseClicked

    private void ButCadastroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCadastroCActionPerformed
        String nome = TxtNomeC.getText();
        String login = TxtUserC.getText();
        String senha = String.copyValueOf(TxtSenhaC.getPassword());
        String senhar = String.copyValueOf(TxtSenhaRC.getPassword());
        String tipo = CBoxTipoC.getSelectedItem() + "";
        UserBO cadastroBo = new UserBO();
        try {
            if (cadastroBo.cadastrar(login, nome, senha, senhar, tipo)) {
                MensagensUtil.addMsg(MainFrame.this, "Cadastro efetuado com sucesso!");
                TabUsuarios.setSelectedComponent(ListaUsuario);
                atualizarTabela();
            } else {
                MensagensUtil.addMsg(MainFrame.this, "Falha no cadastro.");
            }
        } catch (NegocioException ex) {
            ex.printStackTrace();
            MensagensUtil.addMsg(MainFrame.this, ex.getMessage());
        } finally {
            limparCampos();
        }
    }//GEN-LAST:event_ButCadastroCActionPerformed

    private void ButAtualizarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAtualizarLActionPerformed
        atualizarTabela();
    }//GEN-LAST:event_ButAtualizarLActionPerformed

    private void ButExcluirAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExcluirAActionPerformed
        String id = TxtIdA.getText();
        String senha = String.copyValueOf(TxtSenhaA.getPassword());
        UserBO excluirBo = new UserBO();
        try {
            if (excluirBo.excluir(id, senha)) {
                MensagensUtil.addMsg(MainFrame.this, "Excluido com sucesso!");
                TabUsuarios.setSelectedComponent(ListaUsuario);
                atualizarTabela();
            } else {
                MensagensUtil.addMsg(MainFrame.this, "Falha ao excluir.");
            }
        } catch (NegocioException ex) {
            ex.printStackTrace();
            MensagensUtil.addMsg(MainFrame.this, ex.getMessage());
        } finally {
            limparCampos();
        }
    }//GEN-LAST:event_ButExcluirAActionPerformed

    private void ButAlterarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAlterarAActionPerformed
        String id = TxtIdA.getText();
        String login = TxtLoginA.getText();
        String nome = TxtNomeA.getText();
        String senha = String.copyValueOf(TxtSenhaA.getPassword());
        String tipo = CBoxTipoA.getSelectedItem() + "";
        String senhan = String.copyValueOf(TxtSenhaNA.getPassword());
        String senhan2 = String.copyValueOf(TxtSenhaN2A.getPassword());
        UserBO alterarBo = new UserBO();
        try {
            if (alterarBo.alterar(id, login, nome, senha, tipo, senhan, senhan2)) {
                MensagensUtil.addMsg(MainFrame.this, "Alterado com sucesso!");
                TabUsuarios.setSelectedComponent(ListaUsuario);
                atualizarTabela();
            } else {
                MensagensUtil.addMsg(MainFrame.this, "Falha na alteração.");
            }
        } catch (NegocioException ex) {
            ex.printStackTrace();
            MensagensUtil.addMsg(MainFrame.this, ex.getMessage());
        } finally {
            limparCampos();
        }
    }//GEN-LAST:event_ButAlterarAActionPerformed

    private void ButBuscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButBuscarBActionPerformed
        List<UserDTO> lista = new ArrayList<>();
        String id = TxtIdB.getText();
        String nome = TxtNomeB.getText();
        String login = TxtLoginB.getText();
        UserBO buscarBO = new UserBO();
        try {
            Integer tipo = UserBO.escolherTipo(CBoxTipoB.getSelectedItem() + "");
            lista = buscarBO.busca(id, login, nome, tipo);
            TabUsuarios.setSelectedComponent(ListaUsuario);
            atualizarTabela(lista);
        } catch (NegocioException ex) {
            ex.printStackTrace();
            MensagensUtil.addMsg(MainFrame.this, ex.getMessage());
        }
    }//GEN-LAST:event_ButBuscarBActionPerformed

    private void ButLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLogoutActionPerformed
        this.dispose();
        LoginFrame login = new LoginFrame();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        Main.setUsuarioLogado(null);
    }//GEN-LAST:event_ButLogoutActionPerformed

    private void TblPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblPedidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TblPedidoMouseClicked

    private void ButAtualizarPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAtualizarPLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButAtualizarPLActionPerformed

    private void TblProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblProdutoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TblProdutoMouseClicked

    private void ButAtualizarPrLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAtualizarPrLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButAtualizarPrLActionPerformed

    private void TblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TblClienteMouseClicked

    private void ButAtualizarCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAtualizarCLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButAtualizarCLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlteraCliente;
    private javax.swing.JPanel AlteraPedido;
    private javax.swing.JPanel AlteraProduto;
    private javax.swing.JPanel AlteraUsuario;
    private javax.swing.JPanel BuscaUsuario;
    private javax.swing.JButton ButAlterarA;
    private javax.swing.JButton ButAtualizarCL;
    private javax.swing.JButton ButAtualizarL;
    private javax.swing.JButton ButAtualizarPL;
    private javax.swing.JButton ButAtualizarPrL;
    private javax.swing.JButton ButBuscarB;
    private javax.swing.JButton ButCadastroC;
    private javax.swing.JButton ButExcluirA;
    private javax.swing.JButton ButLogout;
    private javax.swing.JButton ButSair;
    private javax.swing.JComboBox CBoxTipoA;
    private javax.swing.JComboBox CBoxTipoB;
    private javax.swing.JComboBox CBoxTipoC;
    private javax.swing.JPanel CadastroCliente;
    private javax.swing.JPanel CadastroProduto;
    private javax.swing.JPanel CadastroUsuario;
    private javax.swing.JLabel LabIdA;
    private javax.swing.JLabel LabIdB;
    private javax.swing.JLabel LabLoginA;
    private javax.swing.JLabel LabLoginB;
    private javax.swing.JLabel LabLoginC;
    private javax.swing.JLabel LabNomeA;
    private javax.swing.JLabel LabNomeB;
    private javax.swing.JLabel LabNomeC;
    private javax.swing.JLabel LabSenhaA;
    private javax.swing.JLabel LabSenhaC;
    private javax.swing.JLabel LabSenhaNA;
    private javax.swing.JLabel LabSenhaNRA;
    private javax.swing.JLabel LabSenhaRC;
    private javax.swing.JLabel LabTipoA;
    private javax.swing.JLabel LabTipoB;
    private javax.swing.JLabel LabTipoC;
    private javax.swing.JLabel LbLogin;
    private javax.swing.JLabel LbTipo;
    private javax.swing.JPanel ListaCliente;
    private javax.swing.JPanel ListaPedido;
    private javax.swing.JPanel ListaProduto;
    private javax.swing.JPanel ListaUsuario;
    private javax.swing.JPanel Novo;
    private javax.swing.JScrollPane ScrollPaneTab;
    private javax.swing.JScrollPane ScrollPaneTab2;
    private javax.swing.JScrollPane ScrollPaneTab3;
    private javax.swing.JScrollPane ScrollPaneTab4;
    private javax.swing.JTabbedPane TabClientes;
    private javax.swing.JTabbedPane TabPedidos;
    private javax.swing.JTabbedPane TabPrincipal;
    private javax.swing.JTabbedPane TabProdutos;
    private javax.swing.JTabbedPane TabUsuarios;
    private javax.swing.JTable TblCliente;
    private javax.swing.JTable TblPedido;
    private javax.swing.JTable TblProduto;
    private javax.swing.JTable TblUser;
    private javax.swing.JPanel Tipo;
    private javax.swing.JTextField TxtIdA;
    private javax.swing.JTextField TxtIdB;
    private javax.swing.JTextField TxtLoginA;
    private javax.swing.JTextField TxtLoginB;
    private javax.swing.JTextField TxtNomeA;
    private javax.swing.JTextField TxtNomeB;
    private javax.swing.JTextField TxtNomeC;
    private javax.swing.JPasswordField TxtSenhaA;
    private javax.swing.JPasswordField TxtSenhaC;
    private javax.swing.JPasswordField TxtSenhaN2A;
    private javax.swing.JPasswordField TxtSenhaNA;
    private javax.swing.JPasswordField TxtSenhaRC;
    private javax.swing.JTextField TxtUserC;
    private javax.swing.JPanel Usuario;
    // End of variables declaration//GEN-END:variables
}
